package com.ucla.models;

// Generated 01/03/2016 02:05:25 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Accion generated by hbm2java
 */
public class Accion implements java.io.Serializable {

	private int idAccion;
	private EstadoAccion estadoAccion;
	private Socio socio;
	private String nroAccion;
	private float valor;
	private boolean activo = true;
	private Set<Venta> ventas = new HashSet<Venta>(0);
	private Set<Desvinculacion> desvinculacions = new HashSet<Desvinculacion>(0);
	private Set<SolicitudVenta> solicitudVentas = new HashSet<SolicitudVenta>(0);

	public Accion() {
	}

	public Accion(int idAccion, EstadoAccion estadoAccion, String nroAccion,
			float valor, boolean activo) {
		this.idAccion = idAccion;
		this.estadoAccion = estadoAccion;
		this.nroAccion = nroAccion;
		this.valor = valor;
		this.activo = activo;
	}

	public Accion(int idAccion, EstadoAccion estadoAccion, Socio socio,
			String nroAccion, float valor, boolean activo, Set<Venta> ventas,
			Set<Desvinculacion> desvinculacions,
			Set<SolicitudVenta> solicitudVentas) {
		this.idAccion = idAccion;
		this.estadoAccion = estadoAccion;
		this.socio = socio;
		this.nroAccion = nroAccion;
		this.valor = valor;
		this.activo = activo;
		this.ventas = ventas;
		this.desvinculacions = desvinculacions;
		this.solicitudVentas = solicitudVentas;
	}

	public int getIdAccion() {
		return this.idAccion;
	}

	public void setIdAccion(int idAccion) {
		this.idAccion = idAccion;
	}

	public EstadoAccion getEstadoAccion() {
		return this.estadoAccion;
	}

	public void setEstadoAccion(EstadoAccion estadoAccion) {
		this.estadoAccion = estadoAccion;
	}

	public Socio getSocio() {
		return this.socio;
	}

	public void setSocio(Socio socio) {
		this.socio = socio;
	}

	public String getNroAccion() {
		return this.nroAccion;
	}

	public void setNroAccion(String nroAccion) {
		this.nroAccion = nroAccion;
	}

	public float getValor() {
		return this.valor;
	}

	public void setValor(float valor) {
		this.valor = valor;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	public Set<Venta> getVentas() {
		return this.ventas;
	}

	public void setVentas(Set<Venta> ventas) {
		this.ventas = ventas;
	}

	public Set<Desvinculacion> getDesvinculacions() {
		return this.desvinculacions;
	}

	public void setDesvinculacions(Set<Desvinculacion> desvinculacions) {
		this.desvinculacions = desvinculacions;
	}

	public Set<SolicitudVenta> getSolicitudVentas() {
		return this.solicitudVentas;
	}

	public void setSolicitudVentas(Set<SolicitudVenta> solicitudVentas) {
		this.solicitudVentas = solicitudVentas;
	}

}
