package com.ucla.models;

// Generated 01/03/2016 02:05:25 AM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Actividad generated by hbm2java
 */
public class Actividad implements java.io.Serializable {

	private int idActividad;
	private Evento evento;
	private TipoActividad tipoActividad;
	private String descripcion;
	private String condicion;
	private Date fechaTope;
	private Date fechaRealizacion;
	private Integer valorEsperado;
	private Integer valorReal;
	private boolean activo = true;

	public Actividad() {
	}

	public Actividad(int idActividad, Evento evento,
			TipoActividad tipoActividad, String descripcion, String condicion,
			boolean activo) {
		this.idActividad = idActividad;
		this.evento = evento;
		this.tipoActividad = tipoActividad;
		this.descripcion = descripcion;
		this.condicion = condicion;
		this.activo = activo;
	}

	public Actividad(int idActividad, Evento evento,
			TipoActividad tipoActividad, String descripcion, String condicion,
			Date fechaTope, Date fechaRealizacion, Integer valorEsperado,
			Integer valorReal, boolean activo) {
		this.idActividad = idActividad;
		this.evento = evento;
		this.tipoActividad = tipoActividad;
		this.descripcion = descripcion;
		this.condicion = condicion;
		this.fechaTope = fechaTope;
		this.fechaRealizacion = fechaRealizacion;
		this.valorEsperado = valorEsperado;
		this.valorReal = valorReal;
		this.activo = activo;
	}

	public int getIdActividad() {
		return this.idActividad;
	}

	public void setIdActividad(int idActividad) {
		this.idActividad = idActividad;
	}

	public Evento getEvento() {
		return this.evento;
	}

	public void setEvento(Evento evento) {
		this.evento = evento;
	}

	public TipoActividad getTipoActividad() {
		return this.tipoActividad;
	}

	public void setTipoActividad(TipoActividad tipoActividad) {
		this.tipoActividad = tipoActividad;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getCondicion() {
		return this.condicion;
	}

	public void setCondicion(String condicion) {
		this.condicion = condicion;
	}

	public Date getFechaTope() {
		return this.fechaTope;
	}

	public void setFechaTope(Date fechaTope) {
		this.fechaTope = fechaTope;
	}

	public Date getFechaRealizacion() {
		return this.fechaRealizacion;
	}

	public void setFechaRealizacion(Date fechaRealizacion) {
		this.fechaRealizacion = fechaRealizacion;
	}

	public Integer getValorEsperado() {
		return this.valorEsperado;
	}

	public void setValorEsperado(Integer valorEsperado) {
		this.valorEsperado = valorEsperado;
	}

	public Integer getValorReal() {
		return this.valorReal;
	}

	public void setValorReal(Integer valorReal) {
		this.valorReal = valorReal;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

}
