package com.ucla.models;

// Generated 01/03/2016 02:05:25 AM by Hibernate Tools 4.3.1

/**
 * ArchivoAlquiler generated by hbm2java
 */
public class ArchivoAlquiler implements java.io.Serializable {

	private int idArchivoAlquiler;
	private Alquiler alquiler;
	private Archivo archivo;
	private TipoArchivo tipoArchivo;
	private boolean activo = true;

	public ArchivoAlquiler() {
	}

	public ArchivoAlquiler(int idArchivoAlquiler, Alquiler alquiler,
			Archivo archivo, TipoArchivo tipoArchivo, boolean activo) {
		this.idArchivoAlquiler = idArchivoAlquiler;
		this.alquiler = alquiler;
		this.archivo = archivo;
		this.tipoArchivo = tipoArchivo;
		this.activo = activo;
	}

	public int getIdArchivoAlquiler() {
		return this.idArchivoAlquiler;
	}

	public void setIdArchivoAlquiler(int idArchivoAlquiler) {
		this.idArchivoAlquiler = idArchivoAlquiler;
	}

	public Alquiler getAlquiler() {
		return this.alquiler;
	}

	public void setAlquiler(Alquiler alquiler) {
		this.alquiler = alquiler;
	}

	public Archivo getArchivo() {
		return this.archivo;
	}

	public void setArchivo(Archivo archivo) {
		this.archivo = archivo;
	}

	public TipoArchivo getTipoArchivo() {
		return this.tipoArchivo;
	}

	public void setTipoArchivo(TipoArchivo tipoArchivo) {
		this.tipoArchivo = tipoArchivo;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

}
