package com.ucla.models;

// Generated 01/03/2016 02:05:25 AM by Hibernate Tools 4.3.1

/**
 * ArchivoPortal generated by hbm2java
 */
public class ArchivoPortal implements java.io.Serializable {

	private int idArchivoPortal;
	private Archivo archivo;
	private Portal portal;
	private boolean activo = true;

	public ArchivoPortal() {
	}

	public ArchivoPortal(int idArchivoPortal, Archivo archivo, Portal portal,
			boolean activo) {
		this.idArchivoPortal = idArchivoPortal;
		this.archivo = archivo;
		this.portal = portal;
		this.activo = activo;
	}

	public int getIdArchivoPortal() {
		return this.idArchivoPortal;
	}

	public void setIdArchivoPortal(int idArchivoPortal) {
		this.idArchivoPortal = idArchivoPortal;
	}

	public Archivo getArchivo() {
		return this.archivo;
	}

	public void setArchivo(Archivo archivo) {
		this.archivo = archivo;
	}

	public Portal getPortal() {
		return this.portal;
	}

	public void setPortal(Portal portal) {
		this.portal = portal;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

}
