package com.ucla.models;

// Generated 01/03/2016 02:05:25 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * EstadoAccion generated by hbm2java
 */
public class EstadoAccion implements java.io.Serializable {

	private int idEstadoAccion;
	private String nombre;
	private boolean activo = true;
	private Set<Accion> accions = new HashSet<Accion>(0);

	public EstadoAccion() {
	}

	public EstadoAccion(int idEstadoAccion, String nombre, boolean activo) {
		this.idEstadoAccion = idEstadoAccion;
		this.nombre = nombre;
		this.activo = activo;
	}

	public EstadoAccion(int idEstadoAccion, String nombre, boolean activo,
			Set<Accion> accions) {
		this.idEstadoAccion = idEstadoAccion;
		this.nombre = nombre;
		this.activo = activo;
		this.accions = accions;
	}

	public int getIdEstadoAccion() {
		return this.idEstadoAccion;
	}

	public void setIdEstadoAccion(int idEstadoAccion) {
		this.idEstadoAccion = idEstadoAccion;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	public Set<Accion> getAccions() {
		return this.accions;
	}

	public void setAccions(Set<Accion> accions) {
		this.accions = accions;
	}

}
