package com.ucla.models;

// Generated 01/03/2016 02:05:25 AM by Hibernate Tools 4.3.1

/**
 * Foto generated by hbm2java
 */
public class Foto implements java.io.Serializable {

	private int id;
	private Club club;
	private Instalacion instalacion;
	private String url;
	private String nombreFoto;
	private String extencion;
	private boolean publico;
	private boolean activo = true;


	public Foto(int idFoto, String url, String nombreFoto, String extencion,
			boolean publico, boolean activo) {
		this.id = idFoto;
		this.url = url;
		this.nombreFoto = nombreFoto;
		this.extencion = extencion;
		this.publico = publico;
		this.activo = activo;
	}

	public Foto(int idFoto, Club club, Instalacion instalacion, String url,
			String nombreFoto, String extencion, boolean publico, boolean activo) {
		this.id = idFoto;
		this.club = club;
		this.instalacion = instalacion;
		this.url = url;
		this.nombreFoto = nombreFoto;
		this.extencion = extencion;
		this.publico = publico;
		this.activo = activo;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Club getClub() {
		return this.club;
	}

	public void setClub(Club club) {
		this.club = club;
	}

	public Instalacion getInstalacion() {
		return this.instalacion;
	}

	public void setInstalacion(Instalacion instalacion) {
		this.instalacion = instalacion;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getNombreFoto() {
		return this.nombreFoto;
	}

	public void setNombreFoto(String nombreFoto) {
		this.nombreFoto = nombreFoto;
	}

	public String getExtencion() {
		return this.extencion;
	}

	public void setExtencion(String extencion) {
		this.extencion = extencion;
	}

	public boolean isPublico() {
		return this.publico;
	}

	public void setPublico(boolean publico) {
		this.publico = publico;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

}
