package com.ucla.models;

// Generated 01/03/2016 02:05:25 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Grupo generated by hbm2java
 */
public class Grupo implements java.io.Serializable {

	private int idGrupo;
	private String descripcion;
	private boolean activo = true;
	private Set<UsuarioGrupo> usuarioGrupos = new HashSet<UsuarioGrupo>(0);
	private Set<FuncionGrupo> funcionGrupos = new HashSet<FuncionGrupo>(0);

	public Grupo() {
	}

	public Grupo(int idGrupo, String descripcion, boolean activo) {
		this.idGrupo = idGrupo;
		this.descripcion = descripcion;
		this.activo = activo;
	}

	public Grupo(int idGrupo, String descripcion, boolean activo,
			Set<UsuarioGrupo> usuarioGrupos, Set<FuncionGrupo> funcionGrupos) {
		this.idGrupo = idGrupo;
		this.descripcion = descripcion;
		this.activo = activo;
		this.usuarioGrupos = usuarioGrupos;
		this.funcionGrupos = funcionGrupos;
	}

	public int getIdGrupo() {
		return this.idGrupo;
	}

	public void setIdGrupo(int idGrupo) {
		this.idGrupo = idGrupo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	public Set<UsuarioGrupo> getUsuarioGrupos() {
		return this.usuarioGrupos;
	}

	public void setUsuarioGrupos(Set<UsuarioGrupo> usuarioGrupos) {
		this.usuarioGrupos = usuarioGrupos;
	}

	public Set<FuncionGrupo> getFuncionGrupos() {
		return this.funcionGrupos;
	}

	public void setFuncionGrupos(Set<FuncionGrupo> funcionGrupos) {
		this.funcionGrupos = funcionGrupos;
	}

}
