package com.ucla.models;

// Generated 01/03/2016 02:05:25 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Indicador generated by hbm2java
 */
public class Indicador implements java.io.Serializable {

	private int idIndicador;
	private String descripcion;
	private boolean activo = true;
	private Set<IndicadorEvento> indicadorEventos = new HashSet<IndicadorEvento>(
			0);

	public Indicador() {
	}

	public Indicador(int idIndicador, String descripcion, boolean activo) {
		this.idIndicador = idIndicador;
		this.descripcion = descripcion;
		this.activo = activo;
	}

	public Indicador(int idIndicador, String descripcion, boolean activo,
			Set<IndicadorEvento> indicadorEventos) {
		this.idIndicador = idIndicador;
		this.descripcion = descripcion;
		this.activo = activo;
		this.indicadorEventos = indicadorEventos;
	}

	public int getIdIndicador() {
		return this.idIndicador;
	}

	public void setIdIndicador(int idIndicador) {
		this.idIndicador = idIndicador;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	public Set<IndicadorEvento> getIndicadorEventos() {
		return this.indicadorEventos;
	}

	public void setIndicadorEventos(Set<IndicadorEvento> indicadorEventos) {
		this.indicadorEventos = indicadorEventos;
	}

}
