package com.ucla.models;

// Generated 01/03/2016 02:05:25 AM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * InstalacionEvento generated by hbm2java
 */
public class InstalacionEvento implements java.io.Serializable {

	private int idActividadInstalacion;
	private Evento evento;
	private Instalacion instalacion;
	private Date fechaFin;
	private Date fechaInicio;
	private boolean activo = true;

	public InstalacionEvento() {
	}

	public InstalacionEvento(int idActividadInstalacion, Evento evento,
			Instalacion instalacion, Date fechaFin, Date fechaInicio,
			boolean activo) {
		this.idActividadInstalacion = idActividadInstalacion;
		this.evento = evento;
		this.instalacion = instalacion;
		this.fechaFin = fechaFin;
		this.fechaInicio = fechaInicio;
		this.activo = activo;
	}

	public int getIdActividadInstalacion() {
		return this.idActividadInstalacion;
	}

	public void setIdActividadInstalacion(int idActividadInstalacion) {
		this.idActividadInstalacion = idActividadInstalacion;
	}

	public Evento getEvento() {
		return this.evento;
	}

	public void setEvento(Evento evento) {
		this.evento = evento;
	}

	public Instalacion getInstalacion() {
		return this.instalacion;
	}

	public void setInstalacion(Instalacion instalacion) {
		this.instalacion = instalacion;
	}

	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

}
