package com.ucla.models;

// Generated 01/03/2016 02:05:25 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * MotivoDesvinculacion generated by hbm2java
 */
public class MotivoDesvinculacion implements java.io.Serializable {

	private int idMotivoDesvinculacion;
	private String descripcion;
	private boolean activo = true;
	private Set<Desvinculacion> desvinculacions = new HashSet<Desvinculacion>(0);

	public MotivoDesvinculacion() {
	}

	public MotivoDesvinculacion(int idMotivoDesvinculacion, String descripcion,
			boolean activo) {
		this.idMotivoDesvinculacion = idMotivoDesvinculacion;
		this.descripcion = descripcion;
		this.activo = activo;
	}

	public MotivoDesvinculacion(int idMotivoDesvinculacion, String descripcion,
			boolean activo, Set<Desvinculacion> desvinculacions) {
		this.idMotivoDesvinculacion = idMotivoDesvinculacion;
		this.descripcion = descripcion;
		this.activo = activo;
		this.desvinculacions = desvinculacions;
	}

	public int getIdMotivoDesvinculacion() {
		return this.idMotivoDesvinculacion;
	}

	public void setIdMotivoDesvinculacion(int idMotivoDesvinculacion) {
		this.idMotivoDesvinculacion = idMotivoDesvinculacion;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	public Set<Desvinculacion> getDesvinculacions() {
		return this.desvinculacions;
	}

	public void setDesvinculacions(Set<Desvinculacion> desvinculacions) {
		this.desvinculacions = desvinculacions;
	}

}
