package com.ucla.models;

// Generated 19/02/2016 11:51:02 PM by Hibernate Tools 4.3.1



/**
 * PartocinanteEvento generated by hbm2java
 */
public class PartocinanteEvento implements java.io.Serializable {

	private int idPatrocinanteEvento;
	private Evento evento;
	private Patrocinante patrocinante;

	public PartocinanteEvento() {
	}

	public PartocinanteEvento(int idPatrocinanteEvento, Evento evento,
			Patrocinante patrocinante) {
		this.idPatrocinanteEvento = idPatrocinanteEvento;
		this.evento = evento;
		this.patrocinante = patrocinante;
	}

	public int getIdPatrocinanteEvento() {
		return this.idPatrocinanteEvento;
	}

	public void setIdPatrocinanteEvento(int idPatrocinanteEvento) {
		this.idPatrocinanteEvento = idPatrocinanteEvento;
	}

	public Evento getEvento() {
		return this.evento;
	}

	public void setEvento(Evento evento) {
		this.evento = evento;
	}

	public Patrocinante getPatrocinante() {
		return this.patrocinante;
	}

	public void setPatrocinante(Patrocinante patrocinante) {
		this.patrocinante = patrocinante;
	}

}
