package com.ucla.models;

// Generated 01/03/2016 02:05:25 AM by Hibernate Tools 4.3.1

/**
 * Politica generated by hbm2java
 */
public class Politica implements java.io.Serializable {

	private int idPolitica;
	private Club club;
	private UnidadMedida unidadMedida;
	private String descripcion;
	private Long valor;
	private boolean activo = true;

	public Politica() {
	}

	public Politica(int idPolitica, UnidadMedida unidadMedida,
			String descripcion, boolean activo) {
		this.idPolitica = idPolitica;
		this.unidadMedida = unidadMedida;
		this.descripcion = descripcion;
		this.activo = activo;
	}

	public Politica(int idPolitica, Club club, UnidadMedida unidadMedida,
			String descripcion, Long valor, boolean activo) {
		this.idPolitica = idPolitica;
		this.club = club;
		this.unidadMedida = unidadMedida;
		this.descripcion = descripcion;
		this.valor = valor;
		this.activo = activo;
	}

	public int getIdPolitica() {
		return this.idPolitica;
	}

	public void setIdPolitica(int idPolitica) {
		this.idPolitica = idPolitica;
	}

	public Club getClub() {
		return this.club;
	}

	public void setClub(Club club) {
		this.club = club;
	}

	public UnidadMedida getUnidadMedida() {
		return this.unidadMedida;
	}

	public void setUnidadMedida(UnidadMedida unidadMedida) {
		this.unidadMedida = unidadMedida;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Long getValor() {
		return this.valor;
	}

	public void setValor(Long valor) {
		this.valor = valor;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

}
