package com.ucla.models;

// Generated 01/03/2016 02:05:25 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
// Generated 05/03/2016 11:15:24 PM by Hibernate Tools 4.3.1


/**
 * Postulacion generated by hbm2java
 */
public class Postulacion implements java.io.Serializable {

	private int id;
	private MotivoPostulacion motivoPostulacion;
	private Postulado postulado;
	private String fecha;
	private String carnetPadrino1;
	private String carnetPadrino2;
	private boolean aprobado;
	private boolean activo = true;
	private Set<Socio> socios = new HashSet<Socio>(0);
	private Set<Opinion> opinions = new HashSet<Opinion>(0);
	private Set<Venta> ventas = new HashSet<Venta>(0);

	public Postulacion() {
	}

	public Postulacion(int idPostulacion, MotivoPostulacion motivoPostulacion,
					   Postulado postulado, String fecha, String carnetPadrino1,
					   String carnetPadrino2, boolean aprobado, boolean activo) {
		this.id = idPostulacion;
		this.motivoPostulacion = motivoPostulacion;
		this.postulado = postulado;
		this.fecha = fecha;
		this.carnetPadrino1 = carnetPadrino1;
		this.carnetPadrino2 = carnetPadrino2;
		this.aprobado = aprobado;
		this.activo = activo;
	}

	public Postulacion(int idPostulacion, MotivoPostulacion motivoPostulacion,
					   Postulado postulado, String fecha, String carnetPadrino1,
					   String carnetPadrino2, boolean aprobado, boolean activo,
					   Set<Socio> socios, Set<Opinion> opinions, Set<Venta> ventas) {
		this.id = idPostulacion;
		this.motivoPostulacion = motivoPostulacion;
		this.postulado = postulado;
		this.fecha = fecha;
		this.carnetPadrino1 = carnetPadrino1;
		this.carnetPadrino2 = carnetPadrino2;
		this.aprobado = aprobado;
		this.activo = activo;
		this.socios = socios;
		this.opinions = opinions;
		this.ventas = ventas;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public MotivoPostulacion getMotivoPostulacion() {
		return this.motivoPostulacion;
	}

	public void setMotivoPostulacion(MotivoPostulacion motivoPostulacion) {
		this.motivoPostulacion = motivoPostulacion;
	}

	public Postulado getPostulado() {
		return this.postulado;
	}

	public void setPostulado(Postulado postulado) {
		this.postulado = postulado;
	}

	public String getFecha() {
		return this.fecha;
	}

	public void setFecha(String fecha) {
		this.fecha = fecha;
	}

	public String getCarnetPadrino1() {
		return this.carnetPadrino1;
	}

	public void setCarnetPadrino1(String carnetPadrino1) {
		this.carnetPadrino1 = carnetPadrino1;
	}

	public String getCarnetPadrino2() {
		return this.carnetPadrino2;
	}

	public void setCarnetPadrino2(String carnetPadrino2) {
		this.carnetPadrino2 = carnetPadrino2;
	}

	public boolean isAprobado() {
		return this.aprobado;
	}

	public void setAprobado(boolean aprobado) {
		this.aprobado = aprobado;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	public Set<Socio> getSocios() {
		return this.socios;
	}

	public void setSocios(Set<Socio> socios) {
		this.socios = socios;
	}

	public Set<Opinion> getOpinions() {
		return this.opinions;
	}

	public void setOpinions(Set<Opinion> opinions) {
		this.opinions = opinions;
	}

	public Set<Venta> getVentas() {
		return this.ventas;
	}

	public void setVentas(Set<Venta> ventas) {
		this.ventas = ventas;
	}
}