package com.ucla.models;

// Generated 01/03/2016 02:05:25 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Postulado generated by hbm2java
 */
public class Postulado implements java.io.Serializable {

	private int id;
	private Persona persona;
	private boolean activo = true;
	private Set<Postulacion> postulacions = new HashSet<Postulacion>(0);

	public Postulado() {
	}

	public Postulado(int idPostulado, Persona persona, boolean activo) {
		this.id = idPostulado;
		this.persona = persona;
		this.activo = activo;
	}

	public Postulado(int idPostulado, Persona persona, boolean activo,
			Set<Postulacion> postulacions) {
		this.id = idPostulado;
		this.persona = persona;
		this.activo = activo;
		this.postulacions = postulacions;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	public Set<Postulacion> getPostulacions() {
		return this.postulacions;
	}

	public void setPostulacions(Set<Postulacion> postulacions) {
		this.postulacions = postulacions;
	}

}
