package com.ucla.models;

// Generated 19/02/2016 11:51:02 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
/**
 * Proveedor generated by hbm2java
 */
public class Proveedor implements java.io.Serializable {

	private int idProveedor;
	private String nombre;
	private String direccion;
	private String telefono;
	private String correo;
	private Set<ProveedorActividad> proveedorActividads = new HashSet(0);

	public Proveedor() {
	}

	public Proveedor(int idProveedor, String nombre, String direccion,
			String telefono, String correo) {
		this.idProveedor = idProveedor;
		this.nombre = nombre;
		this.direccion = direccion;
		this.telefono = telefono;
		this.correo = correo;
	}

	public Proveedor(int idProveedor, String nombre, String direccion,
			String telefono, String correo, Set<ProveedorActividad> proveedorActividads) {
		this.idProveedor = idProveedor;
		this.nombre = nombre;
		this.direccion = direccion;
		this.telefono = telefono;
		this.correo = correo;
		this.proveedorActividads = proveedorActividads;
	}

	public int getIdProveedor() {
		return this.idProveedor;
	}

	public void setIdProveedor(int idProveedor) {
		this.idProveedor = idProveedor;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public Set<ProveedorActividad> getProveedorActividads() {
		return this.proveedorActividads;
	}

	public void setProveedorActividads(Set<ProveedorActividad> proveedorActividads) {
		this.proveedorActividads = proveedorActividads;
	}

}
