package com.ucla.models;

// Generated 19/02/2016 11:51:02 PM by Hibernate Tools 4.3.1


/**
 * ProveedorActividad generated by hbm2java
 */
public class ProveedorActividad implements java.io.Serializable {

	private int idProveedorActividad;
	private Actividad actividad;
	private Proveedor proveedor;
	private String detalle;

	public ProveedorActividad() {
	}

	public ProveedorActividad(int idProveedorActividad, Actividad actividad,
			Proveedor proveedor) {
		this.idProveedorActividad = idProveedorActividad;
		this.actividad = actividad;
		this.proveedor = proveedor;
	}

	public ProveedorActividad(int idProveedorActividad, Actividad actividad,
			Proveedor proveedor, String detalle) {
		this.idProveedorActividad = idProveedorActividad;
		this.actividad = actividad;
		this.proveedor = proveedor;
		this.detalle = detalle;
	}

	public int getIdProveedorActividad() {
		return this.idProveedorActividad;
	}

	public void setIdProveedorActividad(int idProveedorActividad) {
		this.idProveedorActividad = idProveedorActividad;
	}

	public Actividad getActividad() {
		return this.actividad;
	}

	public void setActividad(Actividad actividad) {
		this.actividad = actividad;
	}

	public Proveedor getProveedor() {
		return this.proveedor;
	}

	public void setProveedor(Proveedor proveedor) {
		this.proveedor = proveedor;
	}

	public String getDetalle() {
		return this.detalle;
	}

	public void setDetalle(String detalle) {
		this.detalle = detalle;
	}

}
