package com.ucla.models;

// Generated 01/03/2016 02:05:25 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Recurso generated by hbm2java
 */
public class Recurso implements java.io.Serializable {

	private int idRecurso;
	private String descripcion;
	private boolean activo = true;
	private Set<RecursoInstalacion> recursoInstalacions = new HashSet<RecursoInstalacion>(
			0);

	public Recurso() {
	}

	public Recurso(int idRecurso, String descripcion, boolean activo) {
		this.idRecurso = idRecurso;
		this.descripcion = descripcion;
		this.activo = activo;
	}

	public Recurso(int idRecurso, String descripcion, boolean activo,
			Set<RecursoInstalacion> recursoInstalacions) {
		this.idRecurso = idRecurso;
		this.descripcion = descripcion;
		this.activo = activo;
		this.recursoInstalacions = recursoInstalacions;
	}

	public int getIdRecurso() {
		return this.idRecurso;
	}

	public void setIdRecurso(int idRecurso) {
		this.idRecurso = idRecurso;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	public Set<RecursoInstalacion> getRecursoInstalacions() {
		return this.recursoInstalacions;
	}

	public void setRecursoInstalacions(
			Set<RecursoInstalacion> recursoInstalacions) {
		this.recursoInstalacions = recursoInstalacions;
	}

}
