package com.ucla.models;

// Generated 01/03/2016 02:05:25 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Reservacion generated by hbm2java
 */
public class Reservacion implements java.io.Serializable {

	private int idReservacion;
	private Instalacion instalacion;
	private Socio socio;
	private Date fechaInicio;
	private short fechaFin;
	private boolean activo = true;
	private Set<Alquiler> alquilers = new HashSet<Alquiler>(0);
	private Set<CalendarioFecha> calendarioFechas = new HashSet<CalendarioFecha>(
			0);

	public Reservacion() {
	}

	public Reservacion(int idReservacion, Instalacion instalacion, Socio socio,
			Date fechaInicio, short fechaFin, boolean activo) {
		this.idReservacion = idReservacion;
		this.instalacion = instalacion;
		this.socio = socio;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.activo = activo;
	}

	public Reservacion(int idReservacion, Instalacion instalacion, Socio socio,
			Date fechaInicio, short fechaFin, boolean activo,
			Set<Alquiler> alquilers, Set<CalendarioFecha> calendarioFechas) {
		this.idReservacion = idReservacion;
		this.instalacion = instalacion;
		this.socio = socio;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.activo = activo;
		this.alquilers = alquilers;
		this.calendarioFechas = calendarioFechas;
	}

	public int getIdReservacion() {
		return this.idReservacion;
	}

	public void setIdReservacion(int idReservacion) {
		this.idReservacion = idReservacion;
	}

	public Instalacion getInstalacion() {
		return this.instalacion;
	}

	public void setInstalacion(Instalacion instalacion) {
		this.instalacion = instalacion;
	}

	public Socio getSocio() {
		return this.socio;
	}

	public void setSocio(Socio socio) {
		this.socio = socio;
	}

	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public short getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(short fechaFin) {
		this.fechaFin = fechaFin;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	public Set<Alquiler> getAlquilers() {
		return this.alquilers;
	}

	public void setAlquilers(Set<Alquiler> alquilers) {
		this.alquilers = alquilers;
	}

	public Set<CalendarioFecha> getCalendarioFechas() {
		return this.calendarioFechas;
	}

	public void setCalendarioFechas(Set<CalendarioFecha> calendarioFechas) {
		this.calendarioFechas = calendarioFechas;
	}

}
