package com.ucla.models;

// Generated 01/03/2016 02:05:25 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Socio generated by hbm2java
 */
public class Socio implements java.io.Serializable {

	private int idSocio;
	private Persona persona;
	private Postulacion postulacion;
	private String nroCarnet;
	private boolean activo = true;
	private Set<Sancion> sancions = new HashSet<Sancion>(0);
	private Set<Accion> accions = new HashSet<Accion>(0);
	private Set<Desvinculacion> desvinculacions = new HashSet<Desvinculacion>(0);
	private Set<Reservacion> reservacions = new HashSet<Reservacion>(0);
	private Set<Afiliado> afiliados = new HashSet<Afiliado>(0);

	public Socio() {
	}

	public Socio(int idSocio, Persona persona, String nroCarnet, boolean activo) {
		this.idSocio = idSocio;
		this.persona = persona;
		this.nroCarnet = nroCarnet;
		this.activo = activo;
	}

	public Socio(int idSocio, Persona persona, Postulacion postulacion,
			String nroCarnet, boolean activo, Set<Sancion> sancions,
			Set<Accion> accions, Set<Desvinculacion> desvinculacions,
			Set<Reservacion> reservacions, Set<Afiliado> afiliados) {
		this.idSocio = idSocio;
		this.persona = persona;
		this.postulacion = postulacion;
		this.nroCarnet = nroCarnet;
		this.activo = activo;
		this.sancions = sancions;
		this.accions = accions;
		this.desvinculacions = desvinculacions;
		this.reservacions = reservacions;
		this.afiliados = afiliados;
	}

	public int getIdSocio() {
		return this.idSocio;
	}

	public void setIdSocio(int idSocio) {
		this.idSocio = idSocio;
	}

	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	public Postulacion getPostulacion() {
		return this.postulacion;
	}

	public void setPostulacion(Postulacion postulacion) {
		this.postulacion = postulacion;
	}

	public String getNroCarnet() {
		return this.nroCarnet;
	}

	public void setNroCarnet(String nroCarnet) {
		this.nroCarnet = nroCarnet;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	public Set<Sancion> getSancions() {
		return this.sancions;
	}

	public void setSancions(Set<Sancion> sancions) {
		this.sancions = sancions;
	}

	public Set<Accion> getAccions() {
		return this.accions;
	}

	public void setAccions(Set<Accion> accions) {
		this.accions = accions;
	}

	public Set<Desvinculacion> getDesvinculacions() {
		return this.desvinculacions;
	}

	public void setDesvinculacions(Set<Desvinculacion> desvinculacions) {
		this.desvinculacions = desvinculacions;
	}

	public Set<Reservacion> getReservacions() {
		return this.reservacions;
	}

	public void setReservacions(Set<Reservacion> reservacions) {
		this.reservacions = reservacions;
	}

	public Set<Afiliado> getAfiliados() {
		return this.afiliados;
	}

	public void setAfiliados(Set<Afiliado> afiliados) {
		this.afiliados = afiliados;
	}

}
