package com.ucla.models;

// Generated 01/03/2016 02:05:25 AM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * SolicitudVenta generated by hbm2java
 */
public class SolicitudVenta implements java.io.Serializable {

	private int idSolicitudVenta;
	private Accion accion;
	private MotivoVenta motivoVenta;
	private String motivo;
	private Date fecha;
	private boolean activo = true;

	public SolicitudVenta() {
	}

	public SolicitudVenta(int idSolicitudVenta, Accion accion,
			MotivoVenta motivoVenta, Date fecha, boolean activo) {
		this.idSolicitudVenta = idSolicitudVenta;
		this.accion = accion;
		this.motivoVenta = motivoVenta;
		this.fecha = fecha;
		this.activo = activo;
	}

	public SolicitudVenta(int idSolicitudVenta, Accion accion,
			MotivoVenta motivoVenta, String motivo, Date fecha, boolean activo) {
		this.idSolicitudVenta = idSolicitudVenta;
		this.accion = accion;
		this.motivoVenta = motivoVenta;
		this.motivo = motivo;
		this.fecha = fecha;
		this.activo = activo;
	}

	public int getIdSolicitudVenta() {
		return this.idSolicitudVenta;
	}

	public void setIdSolicitudVenta(int idSolicitudVenta) {
		this.idSolicitudVenta = idSolicitudVenta;
	}

	public Accion getAccion() {
		return this.accion;
	}

	public void setAccion(Accion accion) {
		this.accion = accion;
	}

	public MotivoVenta getMotivoVenta() {
		return this.motivoVenta;
	}

	public void setMotivoVenta(MotivoVenta motivoVenta) {
		this.motivoVenta = motivoVenta;
	}

	public String getMotivo() {
		return this.motivo;
	}

	public void setMotivo(String motivo) {
		this.motivo = motivo;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

}
