package com.ucla.models;

// Generated 01/03/2016 02:05:25 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * TipoArchivo generated by hbm2java
 */
public class TipoArchivo implements java.io.Serializable {

	private int idTipoArchivo;
	private String nombre;
	private boolean activo = true;
	private Set<ArchivoAlquiler> archivoAlquilers = new HashSet<ArchivoAlquiler>(
			0);

	public TipoArchivo() {
	}

	public TipoArchivo(int idTipoArchivo, String nombre, boolean activo) {
		this.idTipoArchivo = idTipoArchivo;
		this.nombre = nombre;
		this.activo = activo;
	}

	public TipoArchivo(int idTipoArchivo, String nombre, boolean activo,
			Set<ArchivoAlquiler> archivoAlquilers) {
		this.idTipoArchivo = idTipoArchivo;
		this.nombre = nombre;
		this.activo = activo;
		this.archivoAlquilers = archivoAlquilers;
	}

	public int getIdTipoArchivo() {
		return this.idTipoArchivo;
	}

	public void setIdTipoArchivo(int idTipoArchivo) {
		this.idTipoArchivo = idTipoArchivo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	public Set<ArchivoAlquiler> getArchivoAlquilers() {
		return this.archivoAlquilers;
	}

	public void setArchivoAlquilers(Set<ArchivoAlquiler> archivoAlquilers) {
		this.archivoAlquilers = archivoAlquilers;
	}

}
