package com.ucla.models;

// Generated 05/03/2016 11:15:24 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * TipoOpnion generated by hbm2java
 */
public class TipoOpnion implements java.io.Serializable {

	private int id;
	private String descripcion;
	private boolean activo = true;
	private Set<Opinion> opinions = new HashSet<Opinion>(0);

	public TipoOpnion() {
	}

	public TipoOpnion(int idTipoOpninion, String descripcion, boolean activo) {
		this.id = idTipoOpninion;
		this.descripcion = descripcion;
		this.activo = activo;
	}

	public TipoOpnion(int idTipoOpninion, String descripcion, boolean activo,
			Set<Opinion> opinions) {
		this.id = idTipoOpninion;
		this.descripcion = descripcion;
		this.activo = activo;
		this.opinions = opinions;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	public Set<Opinion> getOpinions() {
		return this.opinions;
	}

	public void setOpinions(Set<Opinion> opinions) {
		this.opinions = opinions;
	}

}
