package com.ucla.models;

// Generated 01/03/2016 02:05:25 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * TipoAfiliado generated by hbm2java
 */
public class TipoAfiliado implements java.io.Serializable {

	private int idTipoAfiliado;
	private String descripcion;
	private boolean activo = true;
	private Set<Afiliado> afiliados = new HashSet<Afiliado>(0);

	public TipoAfiliado() {
	}

	public TipoAfiliado(int idTipoAfiliado, String descripcion, boolean activo) {
		this.idTipoAfiliado = idTipoAfiliado;
		this.descripcion = descripcion;
		this.activo = activo;
	}

	public TipoAfiliado(int idTipoAfiliado, String descripcion, boolean activo,
			Set<Afiliado> afiliados) {
		this.idTipoAfiliado = idTipoAfiliado;
		this.descripcion = descripcion;
		this.activo = activo;
		this.afiliados = afiliados;
	}

	public int getIdTipoAfiliado() {
		return this.idTipoAfiliado;
	}

	public void setIdTipoAfiliado(int idTipoAfiliado) {
		this.idTipoAfiliado = idTipoAfiliado;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	public Set<Afiliado> getAfiliados() {
		return this.afiliados;
	}

	public void setAfiliados(Set<Afiliado> afiliados) {
		this.afiliados = afiliados;
	}

}
