package com.ucla.models;

// Generated 19/02/2016 11:51:02 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
/**
 * TipoPolitica generated by hbm2java
 */
public class TipoPolitica implements java.io.Serializable {

	private int idTipoPolitica;
	private String descripcion;
	private Set<Politica> politicas = new HashSet(0);

	public TipoPolitica() {
	}

	public TipoPolitica(int idTipoPolitica) {
		this.idTipoPolitica = idTipoPolitica;
	}

	public TipoPolitica(int idTipoPolitica, String descripcion, Set<Politica> politicas) {
		this.idTipoPolitica = idTipoPolitica;
		this.descripcion = descripcion;
		this.politicas = politicas;
	}

	public int getIdTipoPolitica() {
		return this.idTipoPolitica;
	}

	public void setIdTipoPolitica(int idTipoPolitica) {
		this.idTipoPolitica = idTipoPolitica;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set<Politica> getPoliticas() {
		return this.politicas;
	}

	public void setPoliticas(Set<Politica> politicas) {
		this.politicas = politicas;
	}

}
