package com.ucla.models;

// Generated 01/03/2016 02:05:25 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * TipoEventualidad generated by hbm2java
 */
public class TipoEventualidad implements java.io.Serializable {

	private int idTipoEventualidad;
	private String descripcion;
	private boolean activo = true;
	private Set<Eventualidad> eventualidads = new HashSet<Eventualidad>(0);

	public TipoEventualidad() {
	}

	public TipoEventualidad(int idTipoEventualidad, String descripcion,
			boolean activo) {
		this.idTipoEventualidad = idTipoEventualidad;
		this.descripcion = descripcion;
		this.activo = activo;
	}

	public TipoEventualidad(int idTipoEventualidad, String descripcion,
			boolean activo, Set<Eventualidad> eventualidads) {
		this.idTipoEventualidad = idTipoEventualidad;
		this.descripcion = descripcion;
		this.activo = activo;
		this.eventualidads = eventualidads;
	}

	public int getIdTipoEventualidad() {
		return this.idTipoEventualidad;
	}

	public void setIdTipoEventualidad(int idTipoEventualidad) {
		this.idTipoEventualidad = idTipoEventualidad;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	public Set<Eventualidad> getEventualidads() {
		return this.eventualidads;
	}

	public void setEventualidads(Set<Eventualidad> eventualidads) {
		this.eventualidads = eventualidads;
	}

}
