package com.ucla.models;

// Generated 01/03/2016 02:05:25 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * TipoNoticia generated by hbm2java
 */
public class TipoNoticia implements java.io.Serializable {

	private int idTipoNoticia;
	private String descripcion;
	private String color;
	private boolean activo = true;
	private Set<Noticia> noticias = new HashSet<Noticia>(0);

	public TipoNoticia() {
	}

	public TipoNoticia(int idTipoNoticia, String descripcion, boolean activo) {
		this.idTipoNoticia = idTipoNoticia;
		this.descripcion = descripcion;
		this.activo = activo;
	}

	public TipoNoticia(int idTipoNoticia, String descripcion, String color,
			boolean activo, Set<Noticia> noticias) {
		this.idTipoNoticia = idTipoNoticia;
		this.descripcion = descripcion;
		this.color = color;
		this.activo = activo;
		this.noticias = noticias;
	}

	public int getIdTipoNoticia() {
		return this.idTipoNoticia;
	}

	public void setIdTipoNoticia(int idTipoNoticia) {
		this.idTipoNoticia = idTipoNoticia;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	public Set<Noticia> getNoticias() {
		return this.noticias;
	}

	public void setNoticias(Set<Noticia> noticias) {
		this.noticias = noticias;
	}

}
