package com.ucla.models;

// Generated 01/03/2016 02:05:25 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * UnidadMedida generated by hbm2java
 */
public class UnidadMedida implements java.io.Serializable {

	private int idUnidadMedida;
	private String nombre;
	private boolean activo = true;
	private Set<Politica> politicas = new HashSet<Politica>(0);

	public UnidadMedida() {
	}

	public UnidadMedida(int idUnidadMedida, String nombre, boolean activo) {
		this.idUnidadMedida = idUnidadMedida;
		this.nombre = nombre;
		this.activo = activo;
	}

	public UnidadMedida(int idUnidadMedida, String nombre, boolean activo,
			Set<Politica> politicas) {
		this.idUnidadMedida = idUnidadMedida;
		this.nombre = nombre;
		this.activo = activo;
		this.politicas = politicas;
	}

	public int getIdUnidadMedida() {
		return this.idUnidadMedida;
	}

	public void setIdUnidadMedida(int idUnidadMedida) {
		this.idUnidadMedida = idUnidadMedida;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	public Set<Politica> getPoliticas() {
		return this.politicas;
	}

	public void setPoliticas(Set<Politica> politicas) {
		this.politicas = politicas;
	}

}
