package com.ucla.models;

// Generated 01/03/2016 02:05:25 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private int id;
	private Persona persona;
	private String contrasenna;
	private String username;
	private String pregunta;
	private String respuesta;
	private String fecha;
	private boolean activo = true;
	private Set<UsuarioGrupo> usuarioGrupos = new HashSet<UsuarioGrupo>(0);
	private Set<Opinion> opinions = new HashSet<Opinion>(0);
	private Set<Sugerencia> sugerencias = new HashSet<Sugerencia>(0);

	public Usuario() {
	}

	public Usuario(int idUsuario, Persona persona, String contrasenna,
			String username, String pregunta, String respuesta, String fecha,
			boolean activo) {
		this.id = idUsuario;
		this.persona = persona;
		this.contrasenna = contrasenna;
		this.username = username;
		this.pregunta = pregunta;
		this.respuesta = respuesta;
		this.fecha = fecha;
		this.activo = activo;
	}

	public Usuario(int idUsuario, Persona persona, String contrasenna,
			String username, String pregunta, String respuesta, String fecha,
			boolean activo, Set<UsuarioGrupo> usuarioGrupos,
			Set<Opinion> opinions, Set<Sugerencia> sugerencias) {
		this.id = idUsuario;
		this.persona = persona;
		this.contrasenna = contrasenna;
		this.username = username;
		this.pregunta = pregunta;
		this.respuesta = respuesta;
		this.fecha = fecha;
		this.activo = activo;
		this.usuarioGrupos = usuarioGrupos;
		this.opinions = opinions;
		this.sugerencias = sugerencias;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	public String getContrasenna() {
		return this.contrasenna;
	}

	public void setContrasenna(String contrasenna) {
		this.contrasenna = contrasenna;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPregunta() {
		return this.pregunta;
	}

	public void setPregunta(String pregunta) {
		this.pregunta = pregunta;
	}

	public String getRespuesta() {
		return this.respuesta;
	}

	public void setRespuesta(String respuesta) {
		this.respuesta = respuesta;
	}

	public String getFecha() {
		return this.fecha;
	}

	public void setFecha(String fecha) {
		this.fecha = fecha;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	public Set<UsuarioGrupo> getUsuarioGrupos() {
		return this.usuarioGrupos;
	}

	public void setUsuarioGrupos(Set<UsuarioGrupo> usuarioGrupos) {
		this.usuarioGrupos = usuarioGrupos;
	}

	public Set<Opinion> getOpinions() {
		return this.opinions;
	}

	public void setOpinions(Set<Opinion> opinions) {
		this.opinions = opinions;
	}

	public Set<Sugerencia> getSugerencias() {
		return this.sugerencias;
	}

	public void setSugerencias(Set<Sugerencia> sugerencias) {
		this.sugerencias = sugerencias;
	}

}
