package com.ucla.models;

// Generated 01/03/2016 02:05:25 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Venta generated by hbm2java
 */
public class Venta implements java.io.Serializable {

	private int idVenta;
	private Accion accion;
	private Date fecha;
	private float monto;
	private boolean activo = true;
	private Set<Postulacion> postulacions = new HashSet<Postulacion>(0);

	public Venta() {
	}

	public Venta(int idVenta, Accion accion, Date fecha, float monto,
			boolean activo) {
		this.idVenta = idVenta;
		this.accion = accion;
		this.fecha = fecha;
		this.monto = monto;
		this.activo = activo;
	}

	public Venta(int idVenta, Accion accion, Date fecha, float monto,
			boolean activo, Set<Postulacion> postulacions) {
		this.idVenta = idVenta;
		this.accion = accion;
		this.fecha = fecha;
		this.monto = monto;
		this.activo = activo;
		this.postulacions = postulacions;
	}

	public int getIdVenta() {
		return this.idVenta;
	}

	public void setIdVenta(int idVenta) {
		this.idVenta = idVenta;
	}

	public Accion getAccion() {
		return this.accion;
	}

	public void setAccion(Accion accion) {
		this.accion = accion;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public float getMonto() {
		return this.monto;
	}

	public void setMonto(float monto) {
		this.monto = monto;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	public Set<Postulacion> getPostulacions() {
		return this.postulacions;
	}

	public void setPostulacions(Set<Postulacion> postulacions) {
		this.postulacions = postulacions;
	}

}
