package com.ucla.models;

// Generated 19/02/2016 11:51:02 PM by Hibernate Tools 4.3.1



/**
 * VisitaEvento generated by hbm2java
 */
public class VisitaEvento implements java.io.Serializable {

	private int idVisitaEvento;
	private Evento evento;
	private Visita visita;

	public VisitaEvento() {
	}

	public VisitaEvento(int idVisitaEvento, Evento evento, Visita visita) {
		this.idVisitaEvento = idVisitaEvento;
		this.evento = evento;
		this.visita = visita;
	}

	public int getIdVisitaEvento() {
		return this.idVisitaEvento;
	}

	public void setIdVisitaEvento(int idVisitaEvento) {
		this.idVisitaEvento = idVisitaEvento;
	}

	public Evento getEvento() {
		return this.evento;
	}

	public void setEvento(Evento evento) {
		this.evento = evento;
	}

	public Visita getVisita() {
		return this.visita;
	}

	public void setVisita(Visita visita) {
		this.visita = visita;
	}

}
