package com.ucla.models;

// Generated 19/02/2016 11:51:02 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
/**
 * Visita generated by hbm2java
 */
public class Visita implements java.io.Serializable {

	private int idVisita;
	private Afiliado afiliado;
	private Invitado invitado;
	private Socio socio;
	private Date fecha;
	private Date hora;
	private boolean externo;
	private Set<VisitaEvento> visitaEventos = new HashSet(0);

	public Visita() {
	}

	public Visita(int idVisita, Date fecha, Date hora, boolean externo) {
		this.idVisita = idVisita;
		this.fecha = fecha;
		this.hora = hora;
		this.externo = externo;
	}

	public Visita(int idVisita, Afiliado afiliado, Invitado invitado,
			Socio socio, Date fecha, Date hora, boolean externo,
			Set visitaEventos) {
		this.idVisita = idVisita;
		this.afiliado = afiliado;
		this.invitado = invitado;
		this.socio = socio;
		this.fecha = fecha;
		this.hora = hora;
		this.externo = externo;
		this.visitaEventos = visitaEventos;
	}

	public int getIdVisita() {
		return this.idVisita;
	}

	public void setIdVisita(int idVisita) {
		this.idVisita = idVisita;
	}

	public Afiliado getAfiliado() {
		return this.afiliado;
	}

	public void setAfiliado(Afiliado afiliado) {
		this.afiliado = afiliado;
	}

	public Invitado getInvitado() {
		return this.invitado;
	}

	public void setInvitado(Invitado invitado) {
		this.invitado = invitado;
	}

	public Socio getSocio() {
		return this.socio;
	}

	public void setSocio(Socio socio) {
		this.socio = socio;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	public boolean isExterno() {
		return this.externo;
	}

	public void setExterno(boolean externo) {
		this.externo = externo;
	}

	public Set<VisitaEvento> getVisitaEventos() {
		return this.visitaEventos;
	}

	public void setVisitaEventos(Set<VisitaEvento> visitaEventos) {
		this.visitaEventos = visitaEventos;
	}

}
